// This file was generated by Dashcode from Apple Inc.
// DO NOT EDIT - This file is maintained automatically by Dashcode.
var attributes = {
    feedURL: 'http://wap.trivalg.de/kath/index.rss',
    numItemsToShow: "-1",
    maxAgeToShow: "-1",
    showDate: "1",
    showUpdateBadge: "0"
};
