// This file was generated by Dashcode from Apple Inc.
// DO NOT EDIT - This file is maintained automatically by Dashcode.
function setupParts() {
    if (setupParts.called) return;
    setupParts.called = true;
    CreateShape('topRectangleShape', { rightImageWidth: 12, leftImageWidth: 12 });
    CreateText('feedTitle', { text: 'Mein RSS-Feed' });
    CreateButton('button', { text: 'Aktualisieren', onclick: 'refreshFeed', rightImageWidth: 1, leftImageWidth: 1 });
    CreateText('heading', { text: 'Text' });
}
window.addEventListener('load', setupParts, false);
